// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://attqsvaofnoctctqumvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0dHFzdmFvZm5vY3RjdHF1bXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzE2MzAsImV4cCI6MjA2ODAwNzYzMH0.Ms05gNU-0Ulimuk0V0_o_ksXY58nYrXGbgMOI-bkJn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});